### ISSUE TITLE
Guzzle version is very old

### ISSUE THREAD

**Issue by Metehan** [Jeroen-G/laravel-packager#1]
Problem 1
    - Conclusion: don't install jeroen-g/laravel-packager v0.1
    - Conclusion: remove guzzlehttp/guzzle 6.0.1
    - Installation request for jeroen-g/laravel-packager ^0.1.0@dev -> satisfiable by jeroen-g/laravel-packager[0.1.x-dev, v0.1].
    - Conclusion: don't install guzzlehttp/guzzle 6.0.1
    - jeroen-g/laravel-packager 0.1.x-dev requires guzzlehttp/guzzle ~4.0 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3,
 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[4.0.0, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.0.0-rc.1, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.0.0-rc.2, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.0.1, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.0.2, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.0, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.1, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.2, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.3, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.4, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.5, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.6, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.7, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.1.8, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.2.0, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.2.1, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.2.2, 6.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.2.3, 6.0.1].
    - Installation request for guzzlehttp/guzzle == 6.0.1.0 -> satisfiable by guzzlehttp/guzzle[6.0.1].

**Comment by Jeroen-G** [comment]
Thanks!
