### ISSUE TITLE
[Proposal] New --skeleton flag for the "new" command

### ISSUE THREAD

**Issue by tabacitu** [Jeroen-G/laravel-packager#104]
@Jeroen-G - first of all, great job, I've been using & recommending your package for years. 

How do you feel about making it easier to generate a package using a custom skeleton, just this one time, _without_ having to publish the config file?

```bash
# ---------------------
# CURRENT PROCESS
# ---------------------

# Step 1
php artisan vendor:publish --provider="JeroenG\Packager\PackagerServiceProvider"

# Step 2
# change the config file to pick up a different skeleton

# Step 3
php artisan packager:new MyVendor MyPackage --i

# ---------------------
# PROPOSED PROCESS
# ---------------------
php artisan packager:new MyVendor MyPackage --i --skeleton="http://github.com/SomeVendor/SomePackageSkeleton/archive/master.zip"
```

The way I see it:
- the flag would be optional (if no flag is passed, the current config value would be used)
- this would be a non-breaking change
- I understand in most cases, people perhaps want to use the same skeleton over and over again. But this feature would also make it easy to use different skeletons for each ```php artisan packager:new``` call.

If you like the idea, I'd love to submit a PR with this. Happy to help the package, it's been very useful to me for quite a while 😄 

This feature would be super-useful to people who create Backpack add-ons, since there are quite a few _kinds_ of add-ons, that require slightly different things (facades, configs, views, translations, etc). But I think this would also be useful to others who use custom Skeletons, since it would become a one-step operation, instead of three-step.

What do you think? Should I start working on a PR or not?

**Comment by Jeroen-G** [comment]
Your extensive explanation is just awesome!
Yes, you could definitely add a PR for this feature!

**Comment by Jeroen-G** [comment]
For the interactive step it could be a question instead of a flag though.

**Comment by tabacitu** [comment]
Great! Good catch with the interactive - that'll be even easier. I've just submitted PR #105 . 
I'll close this issue, no point in keeping both the issue and the PR open.
