### ISSUE TITLE
Wrong Provider and Alias in the composer.json file

### ISSUE THREAD

**Issue by armancodes** [Jeroen-G/laravel-packager#106]
Assuming we have a package called: `barryvdh/debugbar`
The service provider and alias are written by this package this way:
```
"extra": {
    "laravel": {
        "providers": [
            "DebugbarServiceProvider"
        ],
        "aliases": {
            "Debugbar": "Debugbar"
        }
    }
},
```

I get the Laravel `PackageRepository.php` line 208 error saying, I couldn't find the `DebugbarServiceProvider` file.

Wrtitng the composer.json file in the package directory this way will solve the issue:
```
"extra": {
    "laravel": {
        "providers": [
            "Barryvdh\\Debugbar\\DebugbarServiceProvider"
        ],
        "aliases": {
            "Debugbar": "Barryvdh\\Debugbar\\Debugbar"
        }
    }
},
```

So the problem is `laravel-packager` doesn't include the full path of both the service provider and alias.

**Comment by Jeroen-G** [comment]
Do you know how to fix it? A PR would be awesome ✨

**Comment by armancodes** [comment]
Sure, I'll try to fix it.

**Comment by armancodes** [comment]
When installing the package for the first time everything is perfect.
But when I create a new package like: `LaravelLoginManager` the package has to make the package name kebab-case instead it does it like this: `laravelloginmanager`.
I changed it to kebab-case manually and ran the command `composer update` it caused the provider and alias an issue.
So I'll close this issue and open a new one about package name kebab-case conversion.

**Comment by Jeroen-G** [comment]
Do you mean this? https://github.com/Jeroen-G/laravel-packager/pull/97

**Comment by armancodes** [comment]
No. It's quite vice versa.
When I run this command:
```
php artisan packager:new LaravelLoginManager
```
The name of the package will be the lower case of it `laravelloginmanager`, but instead it should be kebab case `laravel-login-manager`.

**Comment by Jeroen-G** [comment]
Why does it have to be kebab case? I don't believe that's common practice.

**Comment by armancodes** [comment]
I've never seen a package name like this `laravelpackager`. Your package name is even `laravel-packager`.

**Comment by Jeroen-G** [comment]
Yup, on github/composer, not in the actual namespace.

**Comment by armancodes** [comment]
I didn't mean the namespace. I meant the package name in the `composer.json` file and on some places when it gets all lowercase.
