### ISSUE TITLE
packager:new should accept vendor/name

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/laravel-packager#107]
Hi,

I have been using laravel-packager for a while now, really great work! :)
Is it possible make the command ```packager:new``` to accept a vendor and name in the format of ```vendor/name```?

Thank you.

**Comment by Jeroen-G** [comment]
Sure, based on the presence of a `/` it should be possible, would you be willing to make a PR for this feature?

**Comment by bilogic** [comment]
Yes, certainly. But I have not done a PR before. Let me try and figure it out. Might take some time, but will get back. Thank you.

**Comment by Jeroen-G** [comment]
Let me know if you need help!

**Comment by sebastienheyd** [comment]
Just added the same to `package:remove`with PR #112 

And to `package:get` and  `package:git` with PR #111

**Comment by bilogic** [comment]
thanks @sebastienheyd :)
