### ISSUE TITLE
Should list cURL as a requirement

### ISSUE THREAD

**Issue by landjea** [Jeroen-G/laravel-packager#11]
I get the following error message when I try to use your package.

```
[GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.ht
  ml)
```

I can not use cURL in my environment (behind a proxy) so I guess it's a non-starter. So just thought I should let you know that it is a requirement of being able to use your package.

Thanks.

**Comment by Jeroen-G** [comment]
It rather looks like there are problems with some SSL certificate. Both cURL and Guzzle seem to have some documentation on this. I also believe Guzzle can be configured to work without cURL, so there is still an opportunity for you :wink:

**Comment by landjea** [comment]
Ah man, that's my bad. I saw the cURL error and just jumped to the usual cURL issue with my environment. Didn't look any further. Good to hear, I was already mapping out in my head how to recreate your package for my own usage without cURL.

I will check Guzzle tomorrow to see if I can get around this issue. I've never used/installed it before so I am not too sure where I am going to configure it from since it is only being required with your package. Hopefully the docs on that are clear enough. :) Thanks again.

**Comment by Jeroen-G** [comment]
Thanks for elaborating on the solution, good luck with the package! :+1:

**Comment by landjea** [comment]
Thanks. Just as an update for anyone having the same issue : my proposed solution _(above)_ didn't work for me. Received a new error. _(error 52, received empty zip file)_. So I downloaded the zip file manually and added that zipfile to the src files on my local machine. I then added an option to use the zip file locally. _[ sometimes I work from home and curl is fine there, so I wanted the choice for local zip (which could go out of date) or the github version ]_ Then I wrapped it in an if/else statement checking if the command option was there so that I could use the appropriate zip file.

Diff : https://github.com/landjea/laravel-packager/commit/ddb5e52d61ada254e92ac3c2b9f7cd5a2ac1aa6b

_Note: I haven't uploaded the zip file on github. Just to my local machine. So if anyone uses the change ( I know...slim chance of that :wink: ) be sure to remember that you have to add the zip file from https://github.com/thephpleague/skeleton/archive/master.zip to your /laravel-packager/src/ folder (with the stub and command files)._

Thanks again. Gonna close this issue since I have it working. :smile:

**Comment by Jeroen-G** [comment]
Actually, I think I might implement this in the package. I just got the same error myself :smile: 
I found the problem to be the verify option of curl, which on windows leads to an error because there is no certificate present or something like that. https://guzzle.readthedocs.org/en/latest/request-options.html#verify-option

**Comment by landjea** [comment]
Cool. (not about you having the error of course)

Don't forget to add the zip file and notice that I don't actually care what they put for "local" I just check if it can be evaluated. Saves having to code in and check against a positive value such as "Yes" or "true" or "YAY" or "make it so" or whatever they want for "yes" in whatever language. It also means that someone putting "no" or "not" or "false" will still evaluate true. So, I don't know if that is a concern for you or not, but I thought I would mention it.

Also, #12 is a bit of bug that could use the quick fix PR I sent. :wink:

**Comment by Jeroen-G** [comment]
I found a solution, I will push it to dev-master in a few minutes. If you could test it on your environment, I will create a new release afterwards.

**Comment by landjea** [comment]
Good morning, thanks for this but I got the same error I spoke of above yesterday when I tried to use the verify = false option.   
```
[GuzzleHttp\Exception\ConnectException]
  cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

So I have to stick with the local copy of the zip file option for me.

Thanks anyway. Feel free to close this as I have a working solution. :+1:
