### ISSUE TITLE
PackageNewCommand generates incorrect composer.json

### ISSUE THREAD

**Issue by landjea** [Jeroen-G/laravel-packager#12]
When generating the composer.json file, the string search/replace strips out "league/:packagename" which works fine for the "name" attribute but ends up with a malformed github link in the "homepage" attribute.

_example of generated composer.json with error_
`"name": "Landjea/TestingPackage", ` :+1: 
`...`
`"homepage": "https://github.com/thephpLandjea/TestingPackage"` :boom: 

The command needs to strip out "thephpleague/:packagename", as well, to fix this. Probably first or else it won't exist when it gets there. I'll send a PR for it.

**Comment by Jeroen-G** [comment]
Thanks for opening an issue and PR.
If you're okay with it, I will just copy the code, you missed an enter and the whitespace is not as aligned as it was. :blush:
