### ISSUE TITLE
Feasible to include App namespace in package?

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/laravel-packager#123]
Hi,

I'm looking to use the `make:controller` etc commands for packages, however they use the `App` namespace by default and there doesn't seem to be an elegant way to intercept the command to change it.

I actually added a `App` namespace into `composer.json` of each package (at the risk of class names conflicts) and then move the controller/model/etc file into the package's `app` folder.
```
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      ...
    }
  },
```
Is there a better way? How are you guys doing it?

**Comment by Jeroen-G** [comment]
If I understand you correctly, you could [publish and change](https://laravel.com/docs/7.x/artisan#stub-customization) the default `make:` stubs.

**Comment by Jeroen-G** [comment]
You should "never" use the App namespace inside a package, because your package is most likely not the app.

**Comment by bilogic** [comment]
This was more a discussion, but since packages since to have taken a backseat in Laravel, i.e. the removal of `workbench` command, I thought this would be the best place to do that.

I could not think of a way to change the stubs so that they could the namespaced to each package.
And I also don't think it makes sense to rewrite all the make commands for packages.

**Comment by Jeroen-G** [comment]
Now I see what you mean 👍 
I think a series of `make:` commands but for packages would be awesome (although I think separated from Packager).

**Comment by bilogic** [comment]
I found it odd the stubs have namespace variable, yet not configurable by the developer.

Looking up Laravel, I found that it grabs the first namespace in `composer.json` and uses it to namespace the stubs.
https://github.com/laravel/framework/blob/de811ea7f7dc7ecfc686b25fba48e4b0dac473e6/src/Illuminate/Foundation/Application.php#L1315

A bit hacky, but **might** be feasible to manipulate it before passing on to the real `make:` commands.

**Comment by bilogic** [comment]
The manipulation actually worked, looks like I will start a composer package to do this. :) 
But I still would like to hear your opinion on the approach. Thank you.

**Comment by Jeroen-G** [comment]
>  looks like I will start a composer package to do this

Go for it!

**Comment by Jhnbrn90** [comment]
@bilogic Are you aware that there is a package that allows you to use a lot of make commands for a package? Check out https://github.com/beyondcode/laravel-package-tools

I still have an open PR which includes some more options.

**Comment by bilogic** [comment]
@Jhnbrn90 no I'm not. Thanks for pointing out. I will check it in abit, although I already started on mine. Haha.
