### ISSUE TITLE
git commit all files after `packager:new` by default, with option to skip?

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/laravel-packager#126]
The title says it all. Would that be a good idea?
Versioning is a good practice and it makes clear to any new developer the start state of `laravel-packager`.

**Comment by Jhnbrn90** [comment]
@bilogic Do you know of any project that does this? As far as I know Laravel, Vue, NextJS, etc. all initialize a  hit repo but won't include a first commit. 

My guess is that this allows for modification of the bootstrapped code before making a first commit.

**Comment by Jeroen-G** [comment]
My first thought is that I do not see this as part of the package creation process. Since you mention new developers as a target, I think it is best for them to follow a git tutorial from the very start with `git init` to really get a grasp of how it works.

**Comment by bilogic** [comment]
@Jhnbrn90 I'm not aware Laravel does a `git init`.. I have a bash script that installs Laravel with composer followed by a `git init` and `git commit`. That's where this idea came from.

My approach is to never touch the Laravel base so that it makes upgrading Laravel much easier. All my code resides in packages initialized by `laravel-packager` :)

My thinking was, since it has to be done everytime and it isn't really an opinionated practice, why not automated it.

Anyway, if there is no support for such an approach, let's drop it. Thank you.

**Comment by Jhnbrn90** [comment]
@bilogic I see you're right 👍 . I thought the laravel installer used to initialize a git repository but I could be wrong 🤷‍♂️. For new projects I do see that they do not initialize git anymore at least.
