### ISSUE TITLE
[Proposal] Also provide kebab-case vendor name and package name when replacing

### ISSUE THREAD

**Issue by tabacitu** [Jeroen-G/laravel-packager#132]
# The Problem

When we create packages with longer vendor names or package names, the `lowercase` version is used across the package, wherever `StudlyCase` is not used, thanks to [this bit](https://github.com/Jeroen-G/laravel-packager/blob/master/src/Commands/NewPackage.php#L121-L131). For example inside `composer.json`:
- `VendorName\MyPackageName` will become `vendorname/mypackagename`;
- `JeroenG\LaravelPackager` will become `jeroeng/laravelpackager`;

I would argue that in some places (like inside `composer.json`) what you expect is actually using `kebab-case` instead of `lowercase`, since that would be a more legible option, and a lot of composer packages are named that way. So:
- `VendorName\MyPackageName` would become `vendor-name/my-package-name`;
- `JeroenG\LaravelPackager` would become `jeroen-g/laravel-packager`;

Personally, I find myself going through the package each time, to turn `lowercase` into `kebab-case` in a few places. But maybe it's just me.

# The Solution

I propose we either:
- (A) use `kebab-case` as a default if a few places (up for debate where);
- (B) offer an option for skeletons to replace the placeholder with the `kebab-case` version; just like we have `:uc:vendor, :uc:package, :lc:vendor, :lc:package` we could add the `:kc:vendor` and `:kc:package` placeholders, so that skeletons could use them in their `rewriteRules.php`;

Of course, happy to work on a PR if you think it's something you want. Happy to shut up if you don't 🤣 

What do you think @Jeroen-G ? Yay/nay on me submitting a PR for this?

----

Notes:
- I usually use the interactive flag (`--i`)
- discovered this while trying to build [a skeleton for Backpack add-ons](https://github.com/DigitallyHappy/backpack-addon-skeleton)

**Comment by tabacitu** [comment]
@Jeroen-G bump 😀 Do you think this is worth doing? Would you like me to start working on a PR? Would you like me to rephrase/explain the problem better?

**Comment by Jeroen-G** [comment]
❤️ Pull Request

**Comment by tabacitu** [comment]
Just submitted a PR for this - let's move the conversation there: https://github.com/Jeroen-G/laravel-packager/pull/135
