### ISSUE TITLE
Add at least one model, one migration and one seeder

### ISSUE THREAD

**Issue by nefcanto** [Jeroen-G/laravel-packager#139]
Thank you so much for this valuable repository.

However, it's not complete until you provide an end-to-end skeleton to mimic.

Please add at least one model, one migration, one seeder, and one of every possible stuff to your template.

**Comment by Jeroen-G** [comment]
The skeleton is not in this repository, it's [here](https://github.com/Jeroen-G/packager-skeleton).

For numerous reasons I am not planning on expanding the amount of classes in my own skeleton. You should be able to use `php artisan packager:new MyVendor/MyPackage --skeleton="http://github.com/path/to/archive/master.zip` to use your own skeleton. I think that might be a better solution for you (feel free to fork my skeleton!).
