### ISSUE TITLE
Downloading existing package does not have git information

### ISSUE THREAD

**Issue by jdavidbakr** [Jeroen-G/laravel-packager#14]
When using the packager:get command I am unable to make changes and push them back to the repo without checking the package out in another area and then moving it into the packages directory.

**Comment by Jeroen-G** [comment]
That is correct, I stumbled on that too. Do you know how to fix it?

**Comment by jdavidbakr** [comment]
I hadn't looked at the source code until just now, but I wonder if you can actually use git to retrieve the package instead of downloading it?  Here's an artisan command I found on github gist that is using git:

https://gist.github.com/rufhausen/5e4c746e0150b6aa1d44

He's using exec('git ...') to actually do the git commands, which would work in your package if the URL passed is the clone url.

**Comment by Jeroen-G** [comment]
Thanks! When I have the time, I will see if I can do something with it.

**Comment by Jeroen-G** [comment]
Version 1.2 will solve this. It turned out not to be hard at all.
Thanks for all your feedback!
