### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by rezahmady** [Jeroen-G/laravel-packager#142]
Please add php 8 support

**Comment by sbrow** [comment]
Could you please explain why you closed this issue? I for one am getting tired of having to append `--ignore-platform-reqs` to all of my composer calls.

**Comment by Jeroen-G** [comment]
> Could you please explain why you closed this issue? I for one am getting tired of having to append `--ignore-platform-reqs` to all of my composer calls.

There is no need to leave it open: there is no bug, there is no (need for) further information, there was little effort in opening it but leaves me with the burden of spending free time. If you look through all tickets you will notice how enthousiastic I respond to those who are the exact opposite of this issue: they are a Pull Request or an issue with a detailed question, problem, background information, etc. etc.

For any "add X" request in my direction there are three options: pay me to do it, open a PR and collaborate with me or wait until I feel like wanting to work on the feature.
