### ISSUE TITLE
Vendor name is getting studly_case applied to it?

### ISSUE THREAD

**Issue by jdavidbakr** [Jeroen-G/laravel-packager#15]
It appears that when installing a package the vendor name is getting studly_case applied to it.  My git username is jdavidabkr, and my packages are namespaced as jdavidbakr/foo and jdavidbakr/bar.  However, when I create a new package both the composer.json and the config/app file are setting the namespace to Jdavidbakr/foo and Jdavidbakr/bar which is causing the classes to not resolve.

**Comment by Jeroen-G** [comment]
It is sort of common practice in Laravel to namespace it with capitals I believe.
If you want it all lowercase, go to `src/PackagerNewCommand.php` and within the beginning of the `handle()` function, remove the `ucfirst()` functions.
The same goes for the get command in `src/PackagerGetCommand.php`

**Comment by jdavidbakr** [comment]
Is this something you'd be willing to change in the official release?  To me, I would expect the command to require the proper capitalization.

**Comment by Jeroen-G** [comment]
So you suggest to just copy the namespaces as they were spelled in the command?

**Comment by jdavidbakr** [comment]
Yes, that was my personal expectation about how it was going to work.
