### ISSUE TITLE
Problem when run packages with laravel 9.0

### ISSUE THREAD

**Issue by ms08-067** [Jeroen-G/laravel-packager#154]
- Root composer.json requires yaap/theme ^4.1 -> satisfiable by yaap/theme[4.1.0].
    - yaap/theme 4.1.0 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.19).

**Comment by Jeroen-G** [comment]
How does this relate to my package?
