### ISSUE TITLE
Adding additional dependencies 

### ISSUE THREAD

**Issue by codetestmg** [Jeroen-G/laravel-packager#155]
@Jeroen-G  thanks for the library. It's really helpful. I have a custom package where it needs a few illuminate packages and some third-party packages.

May I know any command to add dependencies to the composer file while updating root packages it should install in the root project vendor?

is it manually needed to mention in composer.json file?

Thanks

**Comment by Jeroen-G** [comment]
Hi! What I normally do is require them in my root project and only in the end when I'm nearly finished I start working on the dependencies of the package.
