### ISSUE TITLE
Non-static method Rabol\Testpackage\Testpackage::test() cannot be called statically

### ISSUE THREAD

**Issue by rabol** [Jeroen-G/laravel-packager#156]
Hi

I have created a new package:

 artisan packager:new rabol testpackage  

then created a new method in the Testpackage.php file

```
public function test()
    {
        debug('test');
    }
````

but when I try to use it like this:

Testpackage::test()

I get this error:

```
Non-static method Rabol\Testpackage\Testpackage::test() cannot be called statically
```

looks like the facade is not configured correctly

Laravel v9.34.0
php v8.1.11

**Comment by Jeroen-G** [comment]
I haven't used custom facades in a long time so I can't help you here. If there is anything wrong with the skeleton, let me know!
