### ISSUE TITLE
copy from the github page does not work

### ISSUE THREAD

**Issue by rabol** [Jeroen-G/laravel-packager#162]
Hi

I know that this is a cosmetic, however still annoyoing :)

if one try to copy the installtion command you will get this:

```
$ composer require jeroen-g/laravel-packager --dev
```

please observe the $ sign, that will result in an error

```
zsh: command not found: $
```

**Comment by Jeroen-G** [comment]
If you'd make a Pull Request to remove that I'll be more than happy to merge it 🙂
