### ISSUE TITLE
[InvalidArgumentException] Command "packager" is not defined.

### ISSUE THREAD

**Issue by mubassirhayat** [Jeroen-G/laravel-packager#17]
I have the same issue, I run the composer command and added the service provider in the config/app.php but packager command is not registered!

**Comment by Jeroen-G** [comment]
Did you run `composer dumpautoload`?
Which stepts do you exactly take before this errors shows up?

**Comment by mubassirhayat** [comment]
I installed the package through composer and added the service provider.

**Comment by Jeroen-G** [comment]
And then the message appeared on you screen? Or did you typ anything in the console?
It is very common to have to run `composer dumpautoload` after installing a package.

**Comment by mubassirhayat** [comment]
I typed the command `php artisan packager:new _myverdor mypackage_` in the command line that's when I got the error

**Comment by Jeroen-G** [comment]
Is the command listed when you run `artisan list` ?

**Comment by mubassirhayat** [comment]
no it is not i have checked it again again

**Comment by mubassirhayat** [comment]
No worries I got it, some of my files had restricted access for apache. Got it right now. Thanks a lot for the prompt replies

**Comment by Hemich** [comment]
I do all of this = but i have error message Command "packager" is not defined.

**Comment by Jeroen-G** [comment]
`packager` is not a command, `packager:new`, `packager:get`, etc. are.

**Comment by Hemich** [comment]
php artisan packager:new Hemich products
- i do this and hetting this error

**Comment by Jeroen-G** [comment]
Okay. This problem has always something to do with Laravel & Composer not being able to find the classes, either because the service provider is not loaded or the autoload is out of date.
If your command line return any more information, please post them. If not, try reinstalling, with `composer dumpautoload` before and after the installation.

**Comment by Hemich** [comment]
all error message
[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "packager" namespace.

i try reinstall with your method ? but result same

**Comment by Hemich** [comment]
> some of my files had restricted access for apache.

-- what file ? maybe i have this problem too ?

**Comment by Jeroen-G** [comment]
Do you see the commands when you run `php artisan list`?

**Comment by Hemich** [comment]
Ok i try it .. Tomorrow 
Thanks

**Comment by Hemich** [comment]
So. I try.. But no other result (( 
My Steps:
1) Edit composer.json ( delete row "jeroen-g/laravel-packager": "^1.4")
2) composer update
3) php artisan cache:clear
4) composer dumpautoload
5) Edit composer.json ( add row "jeroen-g/laravel-packager": "^1.4")
6) composer update
7) composer dumpautoload

in 5 step 
...
 - Installing jeroen-g/laravel-packager (v1.4)
    Loading from cache

bootstrap\cache\servises.php was recreated but in file didnt have new rows with packeger words

what i do wrong ?

**Comment by Hemich** [comment]
vendor\jeroen-g\laravel-packager\src\PackagerServiceProvider.php exists

**Comment by Hemich** [comment]
i think that problem in my project ! because if i create new project i can install your packeger and it work
Thanks

**Comment by Hemich** [comment]
Create i do this
My mistake was in command php artisan cache:clear
After php artisan config:cache = thats work
