### ISSUE TITLE
Problem with Laravel 11

### ISSUE THREAD

**Issue by ms08-067** [Jeroen-G/laravel-packager#171]
jeroen-g/laravel-packager 2.9.0 not yet support for Laravel 11? how can I use jeroen-g/laravel-packager for Laravel 11?

**Comment by Jeroen-G** [comment]
I forgot to tag the release 🙈

**Comment by Jeroen-G** [comment]
Released 2.10.0

**Comment by ms08-067** [comment]
> Released 2.10.0

Thanks for support
