### ISSUE TITLE
Doesn't Work For Laravel 5.2

### ISSUE THREAD

**Issue by freddiedfre** [Jeroen-G/laravel-packager#18]
I have set the providers to  JeroenG\Packager\PackagerServiceProvider::class instead of 'JeroenG\Packager\PackagerServiceProvider' as per the Laravel 5.2 specifications. 

However when I run the command php artisan packager: new MyVendor MyPackage I get the error below. 

[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "packager" namespace.

Is there a way to work around this? Or Should should I wait for a newer version?

**Comment by Jeroen-G** [comment]
Yes, I should change the readme file, thanks for mentioning!
Regarding that error, did you run `composer dumpautoload` after installing the package?
Most of the times that will solve such issues.

**Comment by Jeroen-G** [comment]
This seems to be similiar to #17

**Comment by freddiedfre** [comment]
Yes I did run composer dumpautoload, I also checked for the list of commands from artisan and the packager command is not included. Let me try it on a fresh install to see if the issue persists.

**Comment by freddiedfre** [comment]
It worked well on a fresh install. 

Thanks

**Comment by RadhaGupta91** [comment]
For me I have install laravel-packager now on 9Jan2021.
Still got There are no commands defined in the "packager" namespace error.
Jeroen can you help me to sort out this please.
