### ISSUE TITLE
Hyphens in Package Names - invalid classes composed

### ISSUE THREAD

**Issue by TheDigitalOrchard** [Jeroen-G/laravel-packager#2]
GetComposer.org states the following about naming packages:
> Note: If you don't know what to use as a vendor name, your GitHub username is usually a good bet. While package names are case insensitive, the convention is all lowercase and dashes for word separation.

Issuing the following, however, blindly creates PHP classes using hyphens instead of dropping the hyphens:

```artisan packager:new My-Vendor My-Package```

I'm fairly new to Composer, and wishing to follow best practices, so if hyphens are frowned upon, let me know. My planned package names are composed of these components: "Namespace-Type-ID", since I will have many packages.

Example:  CMS-Template-001

I don't want to be seeing my classes called "CmsTemplate001", since that's just ugly, even if it's conventional. I would be happy with CMS_Template_001 as a class name, composed from "CMS-Template-001"... maybe this is an option?

Suggestions? Recommendations?

**Comment by TheDigitalOrchard** [comment]
It's also leaving the hyphens in the namespace declarations.

**Comment by TheDigitalOrchard** [comment]
I've read up on PSR-4 and it seems that packages can exist inside of sub-namespaces, so the following would be perfectly ideal for my setup, if it works...

```
/packages
    /Vendor
        /CMS-Template-001
            /src
                /CMS   (note this extra level)
                    /Template-001
                        /TemplateServiceProvider.php
```

This setup would allow me to elegantly organize many of my Template packages within my `\Vendor\CMS\` namespace.

```
namespace Vendor\CMS\Template;

use Illuminate\Support\ServiceProvider;

class TemplateServiceProvider extends ServiceProvider
{
    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register any package services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

Is this compliant, or does the service provider need to be called `CMSTemplateProvider` to be compliant?

**Comment by Jeroen-G** [comment]
Compliant with PSR or Laravel?
The discourse in the Laravel community is more or less: organise it the way you like to work. Just make sure you put the right namespaced path in the providers array of config/app.php.

**Comment by bilogic** [comment]
Hi,

The issue seems to be that many of the modifications made by packager to the ```App``` files introduces fatal errors and cannot be reversed with ```packager:disable```, perhaps an easy way is to throw a message when hyphens are detected in either ```vendor``` or ```package```, saying something along the lines of: if you want to use hyphens, please do it yourself.
