### ISSUE TITLE
Only handles https clones , cannot handle ssh clones . 

### ISSUE THREAD

**Issue by DrudgeRajen** [Jeroen-G/laravel-packager#23]
I tried to clone with SSH, 
`php artisan packager:git git@github.com:repo/rep.git`
but it says 

> 
> [ErrorException]     
>   Undefined offset: 3

**Comment by Jeroen-G** [comment]
That is because it tries to guess the vendor and package names from the url. It was designed to use the http url. Is there an advantage to SSH over HTTP urls?

Have a look at `src/PackagerGitCommand.php`. If you get it to work with both SSH and HTTP with a few adjustments, feel free to open a PR.

**Comment by DrudgeRajen** [comment]
I think keeping both will be better . Using SSH url user will not have to use their password each time . 
If you are fine with it then i will glad to open a PR.

**Comment by Jeroen-G** [comment]
Sure, as I said, if you get it to work with both SSH and HTTP with a few adjustments, feel free to open a PR.
