### ISSUE TITLE
Package breaks Laravel on PHP 5.6

### ISSUE THREAD

**Issue by sworup** [Jeroen-G/laravel-packager#30]
I've been using this package in my project and one of the machines it has to run on has PHP 5.6 installed. 

The package runs fine on PHP7.

The problem is in PackagerHelper.php on line number 195. 
The short `return (app()['composer'])->dumpAutoloads();` you are using there is not allowed in PHP 5.6. 

I think these changes came in with changeset d4332f4202add4a8fdde54031bdc45012f2aa3cb. 

The error that I get is:

```
> php artisan clear-compiled
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /vendor/jeroen-g/laravel-packager/src/PackagerHelper.php on line 195

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  syntax error, unexpected '->' (T_OBJECT_OPERATOR)        
                                                           

Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255
```

**Comment by Jeroen-G** [comment]
If you know a fix I would immediately merge a PR!

**Comment by Jeroen-G** [comment]
For the time being, require v1.5.1 in your composer.json

**Comment by Jeroen-G** [comment]
Version 1.5.3 should resolve the issue. Let me know if you run into trouble again.
