### ISSUE TITLE
 [Symfony\Component\Debug\Exception\FatalErrorException]   syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by lalustineburra** [Jeroen-G/laravel-packager#31]
when i try to use the package using composer i get the error
 [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '->' (T_OBJECT_OPERATOR)

**Comment by Jeroen-G** [comment]
#30
