### ISSUE TITLE
Latest Updates are not compatible with Laravel 5.1

### ISSUE THREAD

**Issue by vogtdominikgit** [Jeroen-G/laravel-packager#32]
Hello,
i wanted to mention that your latest update (1.5.3) is not compatible with Laravel 5.1 since Illuminate\Support\Composer is not included.

Maybe you add another dependency to the composer.json, so future developer do not have to investigate the issue.

**Comment by Jeroen-G** [comment]
Thank you for reporting the issue!
You could go back to, I believe, 1.5.0 or 1.5.1 because of the dumpAutoloads function.

If you figure out a way to support that feature for Laravel 5.1 and up we could work together to implement in.

**Comment by Jeroen-G** [comment]
Which operating system are you on?
I'm very interested if it now works. I've tested it for 5.1 on Windows, but I also want to know if it works on Mac and Linux.

**Comment by SwissWeb** [comment]
This seems to have the issue on my Mac running Homestead. Before was getting this Error :
```
PHP Fatal error:  Class 'Illuminate\Support\Composer' not found in /home/vagrant/Code/multi.dev/vendor/jeroen-g/laravel-packager/src/PackagerHelper.php on line 33

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Illuminate\Support\Composer' not found
```

**Comment by Jeroen-G** [comment]
Thank you for trying it out. I will release a new version.
