### ISSUE TITLE
do i can create view and route ?

### ISSUE THREAD

**Issue by vahidalvandi** [Jeroen-G/laravel-packager#33]
hi , i need a package contain route , controllers , views .

do @Jeroen-G  support this?

**Comment by Jeroen-G** [comment]
This package helps you with the boilerplate for packages, everything else is up to you to create!

**Comment by Jeroen-G** [comment]
From the readme: ` It will create a packages directory, creates the vendor and package directory in it, pulls in a skeleton package, sets up composer.json, creates a service provider, registers the package in config/app.php and the app's composer.json.`

**Comment by judgej** [comment]
I came here looking for this. There are other common things that packages seem to provide over and over - config (published and extended), views, public resources, migrations etc. It would be nice to have a framework to fit all those into. This is all to help create consistency between packages that people create, without having to keep reinventing the wheel and putting things in different places each time.

**Comment by Jeroen-G** [comment]
I'm thinking of providing a default skeleton which could be more laravel specific than the current phpleague skeleton.
I see myself also doing the same things over and over.
