### ISSUE TITLE
EUPL - invalid link .

### ISSUE THREAD

**Issue by willgopublic** [Jeroen-G/laravel-packager#34]
https://github.com/github/choosealicense.com/issues/479
https://github.com/EmidioStani/choosealicense.com/blob/aa28e590b6b5a0062e2d87d7d8daa4b5d69ee63c/_licenses/eupl-1.1.txt
https://joinup.ec.europa.eu/sites/default/files/eupl1.1.-licence-en_0.pdf
.

**Comment by Jeroen-G** [comment]
Feel free to PR the new link.
