### ISSUE TITLE
GuzzleHttp issue

### ISSUE THREAD

**Issue by mostafa6765** [Jeroen-G/laravel-packager#35]
[GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.ht
  ml)

solved..

1.https://curl.haxx.se/ca/cacert.pem download then paste it server php/extras/ssl 
2. search curl in your php.ini then 
```php
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo ="C:\Program Files (x86)\Ampps\php\extras\ssl\cacert.pem"
```

* solved

**Comment by Jeroen-G** [comment]
:+1:
