### ISSUE TITLE
Vendor Namespace and Package Name should be StudlyCased in the namespace

### ISSUE THREAD

**Issue by deweller** [Jeroen-G/laravel-packager#36]
The vendor namespace and package name should be lowercased in the directory tree, but they should be StudlyCased in the class definition.

When I run:
```
$ artisan packager:new tokenly fluentd-logger
```

**The Expected result is:**

Should create a namespace of namespace definition of `Tokenly\FluentdLogger;`

**The actual Result is:**

Creates `namespace tokenly\fluentd-logger;`

Here is an example of capitilization in a Laravel vendor package:

![skeletonclass_php_ _tokenly-dashboard](https://cloud.githubusercontent.com/assets/51414/26729121/1b77d810-4772-11e7-8069-bf7447fa8069.png)
![command_php_ _tokenly-dashboard](https://cloud.githubusercontent.com/assets/51414/26729147/2e630878-4772-11e7-8670-4d1adb536af2.png)

**Comment by Jeroen-G** [comment]
I have seen Laravel packages work without studlycases. It is not programmatically required, and that is why I leave it up to you to define the capitals. Or at least it was that way when I designed Packager. That is also why all examples in the readme have capitals.

**Comment by deweller** [comment]
I guess the problem is that there is no way to generate both a lowercase directory name with a corresponding StudlyCased namespace.  I have to manually edit the namespace in all the generated files.

The nice thing to have here would be the ability to specify the directory name and the namespace separately (with sane defaults).

**Comment by Jeroen-G** [comment]
Changing the directory to lowercase would only require changing the app composer.json I think.

However, I would accept a PR that adds the ability to define the directory's name in the interactive new command (the --i flag)

**Comment by Jeroen-G** [comment]
Closed, waiting for Pull Request.

**Comment by judgej** [comment]
The namespace may be StudyCap cased, but the vendor name and package name and their directories should be *lower case*. You can call the directories whatever you like in the `packages` directory, but the convention for composer is a lower case vendor (e.g. "laraval") and lower case package name (e.g. "framework").

Namespaces and vendor/package names, are two completely different things. For example, the "laravel/framework" vendor/package name provides the "\Illuminate" namespace.

**Comment by Jeroen-G** [comment]
I would welcome a Pull Request.

**Comment by Jeroen-G** [comment]
And still no one makes a PR.
