### ISSUE TITLE
zip file download corrupted i'm fixed this issue

### ISSUE THREAD

**Issue by algmaal** [Jeroen-G/laravel-packager#39]
[ErrorException]                                              
  ZipArchive::extractTo(): Invalid or uninitialized Zip object
i'm fixed this issue
replace function download
 public function olddownload($zipFile, $source)
    {
        $client = new Client(['verify' => env('CURL_VERIFY', true)]);
        $response = $client->get($source);
        file_put_contents($zipFile, $response->getBody());
        return $this;
    }

To 

 public function download($zipFile, $source)
    {
        file_put_contents($zipFile, fopen($source, 'r'), LOCK_EX);
        return $this;
    }

in PackagerHelper.php

**Comment by Jeroen-G** [comment]
This seems an incidental issue, if you (or others) still encounter it feel free to reopen with the stack trace.
