### ISSUE TITLE
How to publish package?

### ISSUE THREAD

**Issue by pawel-miczka** [Jeroen-G/laravel-packager#41]
Is there any way to simple publish package? 
Or should I just in cmd / terminal go to package folder and use:

```cmd
git init && git add --all && git commit -m "my sweet commit" && git add origin master [repo_url] && git push origin master
```

If it's only way then what about new command like

```cmd
php artisan:packager publish
```

It could get repo url from composer.json

**Comment by Jeroen-G** [comment]
I like your idea. I currently have not so much time, are you willing to work on a Pull Request?

**Comment by pawel-miczka** [comment]
I will try but I do not promise.

**Comment by Jeroen-G** [comment]
My first attempt is now on the master branch. Give it a spin. :)

**Comment by pawel-miczka** [comment]
Of course :D
