### ISSUE TITLE
get command doesn't work with Bitbucket

### ISSUE THREAD

**Issue by garhbod** [Jeroen-G/laravel-packager#45]
Maybe an option could be added to the get function.
--host or --provider=Bitbucket
and the url has '/branch/master.zip' appended instead of '/archive/master.zip'

**Comment by Jeroen-G** [comment]
"and the url has '/branch/master.zip' appended instead of '/archive/master.zip'"
Do you mean in general or for bitbucket?

**Comment by garhbod** [comment]
For bitbucket

**Comment by Jeroen-G** [comment]
I have implemented a possible solution, but on the 2.0 branch instead of master. You could try it out, I will consider releasing it in a 1.x release as well.
