### ISSUE TITLE
Publish config and assets 

### ISSUE THREAD

**Issue by dmarcos89** [Jeroen-G/laravel-packager#46]
Hi, first time developing packages for Laravel. Great work by the way!

Quick question, why is it that `php artisan vendor:publish` doesn't display my new package option?

Could you give a quick sample or idea on how to integrate this with Laravel package development??

Thanks!

**Comment by Jeroen-G** [comment]
I assume you already tried dumping the Composer autoloads. Could you post your package service provider?

**Comment by dmarcos89** [comment]
So after dumping composer on my new package things started to work... i was doing it on the root folder..

Thanks anyway!!
