### ISSUE TITLE
[bug] Call to undefined method JeroenG\Packager\Conveyor::packageDir()

### ISSUE THREAD

**Issue by happyDemon** [Jeroen-G/laravel-packager#51]
I get this error after running:
```
php artisan packager:publish HappyDemon EchoServer https://github.com/happyDemon/echo-server.git
```

After digging in the code I'm also unable to find the method.

I've added a pull request #52

**Comment by Jeroen-G** [comment]
Oops, I forgot to change that. Thank you!
