### ISSUE TITLE
Development-only install question

### ISSUE THREAD

**Issue by alariva** [Jeroen-G/laravel-packager#54]
> If you do run the package on Laravel 5.5+, package auto-discovery takes care of the magic of adding the service provider. Be aware that the auto-discovery also means that this package is loaded in your production environment. Therefore you may disable auto-discovery and instead put in your AppServiceProvider something like this:

But I don't get the difference of doing a conditional service provider load vs `composer require --dev`, would that be equally working?. I'm sorry if I'm missing something. Thanks for this great tool.

**Comment by Jeroen-G** [comment]
You are right. The doc could use some tweaking.
`dev` packages however are only _not_ installed when you run `composer install --no-dev`.

**Comment by alariva** [comment]
Yeah, so thats my question. I understand I would only run this package in
local (dev). Or should I have it in prd?

**Comment by Jeroen-G** [comment]
No, you should not have this running in production!

**Comment by alariva** [comment]
Thanks very much for your clarification, and sorry if I'm being persistent on this.

What I'm getting confused at is that the installation instruction is

    $ composer require jeroen-g/laravel-packager

while it seems to me that this would be a better fit:

    $ composer require jeroen-g/laravel-packager --dev

Since most development packages (like for example `barryvdh/laravel-debugbar`) would suggest to install with `--dev`.

I was just wondering that I might miss something for what `composer require jeroen-g/laravel-packager` would be better for some reason.

**Comment by Jeroen-G** [comment]
No, you're not missing something, the docs are :)
