### ISSUE TITLE
packager:publish not work properly

### ISSUE THREAD

**Issue by abkrim** [Jeroen-G/laravel-packager#56]
I run 

`php artisan packager:publish Abkrim AbkCpanel ` 

**Why?**

Command on exec is wron because forget a  semicolon after cd command ";".

I like push a request on github, but i not a great user of github.
I clone your repo, make change, but github say me wrong user & password (usually use SSH Keys) 

**code ok for line 66 on PublishPackage**

exec('cd '.$this->conveyor->packagePath().'; git init && git add --all && git commit -m "Initial commit"');

** bad code **

exec('cd '.$this->conveyor->packagePath().' git init && git add --all && git commit -m "Initial commit"');

Best regards

**Comment by Jeroen-G** [comment]
Regarding pull requests: check this out: https://guides.github.com/activities/forking/

Try again, and if that still does not work I can commit the change myself 👍
