### ISSUE TITLE
After installing with composer I get this error

### ISSUE THREAD

**Issue by hydrarulz** [Jeroen-G/laravel-packager#6]
When i run

    ./artisan

I get

    The command defined in "JeroenG\Packager\PackagerGetCommand" cannot have an empty name.

**Comment by Jeroen-G** [comment]
Why not update to Laravel 5.1?

**Comment by hydrarulz** [comment]
I do have Laravel 5.1
I created a fork and added the $name property. 
https://github.com/ElasticOrange/laravel-packager/commit/69e89f765c542f57e343ca3bb8a396697887883d

But I still get errors after. Maybe I miss configured something?

**Comment by Jeroen-G** [comment]
According to the L5.1 [docs](http://laravel.com/docs/5.1/artisan), the $signature property should provide the name. The default console command in the app ('Inspire') does also work this way.
Did it work with the $name property?
See #3 for a very similar issue.

**Comment by hydrarulz** [comment]
You are right, I have Laravel 5.0

Would this be prevented if the composer.json file contains laravel:5.1.* as a requirement?

**Comment by Jeroen-G** [comment]
Or it would cause more conflict because it will install L5.1 alongside your L5.0?
Could you try putting the laravel 5.1.* requirement in your app composer.json to see what happens?
