### ISSUE TITLE
Usage Question: How to install dependencies

### ISSUE THREAD

**Issue by johntimothybailey** [Jeroen-G/laravel-packager#63]
I've built a package within a test project by `php artisan packager:new MyVendor MyPackage`. Now the `MyPackage` has a dependency on `spatie/laravel-permission`. How do I get the parent package to be aware of this dependency and publish the configuration file?

**Comment by Jeroen-G** [comment]
I've been thinking that there must be a better way to do this, because right now you need to require those dependencies in the parent project as well.

**Comment by johntimothybailey** [comment]
@Jeroen-G I figured it out and will post here with the solution but may be a few days due to workload.

**Comment by johntimothybailey** [comment]
In fact, @Jeroen-G I'm going to create a PR in the docs and you can deny it if you don't want it in the docs (i.e. readme)

**Comment by mfullbrook** [comment]
@johntimothybailey would be really great to understand how you solved this dilemma.

**Comment by molbal** [comment]
@johntimothybailey Hey, did you create the PR? I can't find it and I haven't found a solution myself yet to packages having dependencies
