### ISSUE TITLE
Package API

### ISSUE THREAD

**Issue by payalpandav1** [Jeroen-G/laravel-packager#64]
I have created routes/Api.php file in package. and create one route(Route::get('complaint', 'IndexController@index');) in Api.php file. but when i run this route it returns error "Sorry, the page you are looking for could not be found."  Please let me know how can i run routes which are created in package,

**Comment by Jeroen-G** [comment]
Is [this](https://github.com/Jeroen-G/packager-skeleton/blob/master/src/MyPackageServiceProvider.php#L19) uncommented and adapted for your routes/api.php?
