### ISSUE TITLE
Convert Pascal case to Kebab case

### ISSUE THREAD

**Issue by thomasdominic** [Jeroen-G/laravel-packager#65]
Hi,

is it possible to have a package name like MyAwesomePackage that becomes my-awesome-package rather than myawesomepackage?

**Comment by Jeroen-G** [comment]
Not at this moment, but maybe you can look into how it might be supported :)

**Comment by thomasdominic** [comment]
I can't run test because I have this problem : 
_Declaration of JeroenG\Packager\Tests\TestCase::setUp() must be compatible with Orchestra\Testbench\TestCase::setUp()_

**Comment by Jeroen-G** [comment]
I think that has to do with the new void return type!
