### ISSUE TITLE
[v5.7.28] php artisan packager:remove deletes everything from the vendor

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/laravel-packager#66]
- Laravel Version: 5.7.28
- PHP Version: 7.2.10
- Database Driver & Version: N/A

### Description:
```php artisan packager:remove v1 p1``` is deleting everything inside ```v1```

### Steps To Reproduce:
I have 2 laravel projects ```my-own-packages``` and ```App1```

1. New packages are always created inside ```my-own-packages``` using ```php artisan packager:new v1 p1```
2. ```App1```'s ```composer.json``` contains ```"repositories": [{ "type": "path", "url": "../my-own-package/packages/*/*"}]```, so my own packages can be pulled by running ```composer require v1/p1``` and so on.
3. I do this so that, in time, ```App2``` can re-use ```v1/p1``` via composer
4. While running a ```php artisan packager:remove v1 p1```, artisan deleted several other packages inside ```my-own-packages/packages/v1``` before some permissions issue caused it to throw an exception.
5. Is this by design? Seems more like a bug to me
6. If by design, then is there a way to isolate packages from the app during development? i.e. the package sits inside ```App1/vendor/v1/p1``` instead of ```App1/packages/v1/p1```
7. To workaround, I had to run ```php artisan packager:disable v1 p1``` in ```my-own-packages``` and then manually delete ```my-own-packages/packages/v1/p1```

Thank you.

**Comment by bilogic** [comment]
Sorry, I think I got the wrong repo.

**Comment by Jeroen-G** [comment]
Thank you for being so clear and elaborate! I will look into it asap for you!

**Comment by Jeroen-G** [comment]
During the removal process it should ask `Do you want to remove the vendor directory?` with a default of false. The upcoming release, which is now in `dev-master` changes how packages are installed and removed, and might solve this issue too.
