### ISSUE TITLE
composer.json and config.php files updates although package not installed

### ISSUE THREAD

**Issue by kakposoe** [Jeroen-G/laravel-packager#68]
At the moment, using the `php artisan packager:get` or `php artisan packager:git` commands will still create entries within `config/app.php` and `composer.json` even if the download step is not successful.

This was noticed when trying to perform a `php artisan packager:git` on a package. My github account has 2fa enabled, so authentification failed when trying to download the package. However updates were made to these files.

It would be important to ensure that the package has be installed before updating `composer.json` or `config/app.php`.

**Comment by Jeroen-G** [comment]
Do you have any ideas on how to accomplish that?

**Comment by kakposoe** [comment]
I've submitted a PR #69
