### ISSUE TITLE
Problem with loading helpers.php file

### ISSUE THREAD

**Issue by sasokovacic** [Jeroen-G/laravel-packager#70]
Hi, I've generated new package using your plugin. Everything works ok except helpers.php file.. Composer doesn't dump this file into the autoload_files.php so I can't access functions that are defined it the file... Any idea?

Thanks...

**Comment by Jeroen-G** [comment]
You mean the helpers file from your package?

**Comment by sasokovacic** [comment]
yes.. I added it to the root composer.json file for now but would like to know if I can do it inside of the package root directory... It is actualy set in the package's composer.json file but if I understand correctly this is used when you install the package over the composer install...

**Comment by Jeroen-G** [comment]
You could do it via a service provider as well. Otherwise you would indeed need to put in the root composer.json while developing your package (once deployed it is fine to have it in the package composer.json). So you understood it correctly!

**Comment by sasokovacic** [comment]
Thanks for the answer :)
