### ISSUE TITLE
Incorrect assumption of ServiceProvider class name using git install

### ISSUE THREAD

**Issue by kakposoe** [Jeroen-G/laravel-packager#71]
Using the `packager:git` command, url segments are used to create the service provider class entry in the `config/app.php` file. This will most likely need to incorrect registering of plugin service providers. For example, running the command:

    php artisan packager:git https://github.com/Jeroen-G/laravel-packager

Will result in the following being added to `config/app.php`:

    jeroen-g\laravel-packager\laravel-packagerServiceProvider::class

rather than:

    JeroenG\Packager\PackagerServiceProvider::class

Although `vendor` and `package` can be passed as parameters, running this command without these arguments does not automatically put the default `vendor` and `package` into title case.

Secondly, in the event of the user installing a package with a hyphen, there is no prompt to run the command with the `vendor` and `package` arguments.

**Comment by Jeroen-G** [comment]
> Although vendor and package can be passed as parameters, running this command without these arguments does not automatically put the default vendor and package into title case.

This is indeed something that should be fixed!

**Comment by kakposoe** [comment]
I'll write something towards a solution soon.
