### ISSUE TITLE
Ability to update packages install via git

### ISSUE THREAD

**Issue by kakposoe** [Jeroen-G/laravel-packager#73]
At the moment, there is no way to update packages installed via git repository. This means that in the event of new changes being made to a repository, a `git pull` will have to be ran within the package folder to update to the latest version. There may be scope here to do the following:

### Update command

For example: `php artisan packager:update {vendor?} {package?}`

This could either expect the `package` and `vendor` arguments, or produce a table of installed packages to select a package.

### Extend the list command
The list command could be extended with an additional flag to find out if the packages are behind on their current branch. For example:

    php artisan packager:list --status

**Comment by Jeroen-G** [comment]
I think it is easier to do a git pull in the package folder than a artisan command in the root folder. A `--git` status flag might be cool though!
