### ISSUE TITLE
Bug: dash in package name and first symbol is numeric

### ISSUE THREAD

**Issue by 4n70w4** [Jeroen-G/laravel-packager#80]
`php artisan packager:new 4n70w4 Laravel-OKVED`

```
 0/6 [>---------------------------]   0% Creating package 4n70w4\Laravel-OKVED...
 1/6 [====>-----------------------]  16% Creating packages directory...
 2/6 [=========>------------------]  33% Creating vendor...
 3/6 [==============>-------------]  50% Downloading skeleton...
 4/6 [==================>---------]  66% Replacing skeleton placeholders...
 5/6 [=======================>----]  83% Dumping autoloads and discovering package...
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
 6/6 [============================] 100% Package created successfully!
```

Generated packages/4n70w4/Laravel-OKVED/src/Laravel-OKVED.php:

```php
<?php

namespace 4n70w4\Laravel-OKVED;

class Laravel-OKVED
{
    // Build wonderful things
}
```

1) Incorrect namespace: number as first symbol
2) Incorrect classname: dash in classname

> The class name can be any valid label, provided it is not a PHP reserved word. A valid class name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: ^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$.

https://php.net/manual/en/language.oop5.basic.php

**Comment by Jeroen-G** [comment]
The package does not check if you use valid PHP for your vendor or package, so it is up to you to choose a sensible name.

**Comment by 4n70w4** [comment]
It's time to do this check. Or to give the ability to set the correct namespaces and class-names.

In my case, the name of the vendor and the package are exactly those that I want to receive as a name in the `composer.json` file

**Comment by Jeroen-G** [comment]
I see this as an edge case and unfortunately cannot put time in it to fix it.

**Comment by 4n70w4** [comment]
Maybe I'll do it in a month.

**Comment by stfr** [comment]
Thx, I've the same issue with my organisation name. I'll fix it manually for the moment :)
