### ISSUE TITLE
Bug: package not registered properly after creating?

### ISSUE THREAD

**Issue by zonelsk** [Jeroen-G/laravel-packager#84]
Versions 2.1 and 2.2 on laravel 5.5.* and 5.8.* work fine.
Version 2.3. with laravel 5.8.* and laravel 6.0.* doesn't register package in composer.json and in config/app.php

Section in **config/app.php** 
```
/*
 * Package Service Providers...
 */
```
stays empty and autoload.psr-4 section in **composer.json** has only default line.
```
"autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```
Every scenario was tested on fresh installed project and only one package installed
`composer require jeroen-g/laravel-packager --dev`

after that i only run
`php artisan packager:new zonelsk test`

**Comment by happyDemon** [comment]
@Jeroen-G this is pretty crucial to the package, hope you can merge my pull request soon.
