### ISSUE TITLE
Client error: 404 

### ISSUE THREAD

**Issue by joelmatiassilva** [Jeroen-G/laravel-packager#9]
Hi,

I have an error when i try to run: sudo php artisan packager:get https://github.com/joelmatiassilva/loaderio.git

I see in my console:

 0/5 [>---------------------------]   0% Creating package joelmatiassilva\loaderio.git...
 1/5 [=====>----------------------]  20% Creating packages directory...
 2/5 [===========>----------------]  40% Creating vendor...
 3/5 [================>-----------]  60% Downloading from Github...
                                          
  [GuzzleHttp\Exception\ClientException]  
  Client error: 404                       
---------------------------------------------------------------------------------------------------------------------                                          
Any idea what is happening?

**Comment by Jeroen-G** [comment]
The correct url to use is: https://github.com/joelmatiassilva/loaderiolaravel 
The package uses the github .zip, not the .git.

**Comment by joelmatiassilva** [comment]
thanks!
