### ISSUE TITLE
Add tar.gz skeleton support

### ISSUE THREAD

**Issue by zlodes** [Jeroen-G/laravel-packager#91]
It will be cool ability to use .tar.gz archives as skeleton. 
We are using private packagist and private repos.

By default, packagist uses tar.gz archives and there is no way to get ZIP...

**Comment by Jeroen-G** [comment]
Is this something you feel comfortable to contribute?

**Comment by zlodes** [comment]
If you do not mind, I'll add this feature later. :)

**Comment by zlodes** [comment]
@Jeroen-G added PR #92
