### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by giovannipds** [Jeroen-G/laravel-packager#94]
Hello! I think this issue is supposed to be opened at [packager-skeleton](https://github.com/Jeroen-G/packager-skeleton) but, since they're connected/related, I'm opening it here.

Skeleton is requiring `illuminate/support: "~5"`, because of that, creation of packages for laravel 6 aren't being so easy as it should.

**Comment by Jeroen-G** [comment]
Thanks for mentioning, there's a PR for this on the skeleton repo!
