### ISSUE TITLE
Classes vendor-name package-name not converted to studly (pascal) case

### ISSUE THREAD

**Issue by thewebartisan7** [Jeroen-G/laravel-packager#96]
If I create my package with name like:

`php artisan packager:new my-vendor my-package`

Then I expect that my class names are:

MyVendor MyPackage

but instaed they are:

```php
namespace my-vendor\my-package;

class my-package
{
    // Build wonderful things
}

// service provider
namespace my-vendor\my-package;

use Illuminate\Support\ServiceProvider;

class my-packageServiceProvider extends ServiceProvider
{
//...
}
```

Should not be converted to camel case "my-vendor" and "my-package"?

The package itself would fail if we try to create like this:

`php artisan packager:new jeroen-g laravel-packager`

This could be easy fixed by converting to camel case only the class name and file names, apart vendor and package folder. 

What do you think?

**Comment by Jeroen-G** [comment]
Feel free to send a PR to convert `packager:new jeroen-g laravel-packager` to `packager:new JeroenG LaravelPackager`

**Comment by thewebartisan7** [comment]
I will try to find time this week.

**Comment by thewebartisan7** [comment]
Check here https://github.com/Jeroen-G/laravel-packager/pull/97

As I understand the only command that need to be updated is "new", as it's the only one who rename files and class name of skeleton.

The others should continue to works, but test passed successfully.

I have also added two new tests similar to your others, this:


```php
    public function test_new_package_camelized_is_created()
    {
        Artisan::call('packager:new', ['vendor' => 'my-vendor', 'name' => 'my-package']);

        $this->seeInConsoleOutput('Package created successfully!');
    }

    public function test_new_package_camelized_is_installed()
    {
        Artisan::call('packager:new', ['vendor' => 'my-vendor', 'name' => 'my-package']);

        $composer = file_get_contents(base_path('composer.json'));

        $this->assertStringContainsString('my-vendor/my-package', $composer);
    }
```

If you want to include this, let me know, I will add in IntegratedTest.php or where you want.

<img width="573" alt="Screenshot 2020-01-14 at 07 17 14" src="https://user-images.githubusercontent.com/57477934/72318921-eb14dd80-369d-11ea-8792-451fdbafaf93.png">

**Comment by Jeroen-G** [comment]
👏 👏 👏 

Great to see you added tests as well! Nicely done.

>As I understand the only command that need to be updated is "new", as it's the only one who rename files and class name of skeleton.
No, most of the commands accept a vendor and package name, I think they should all work in the same way. So if you could take a look at it, that would be great.

**Comment by thewebartisan7** [comment]
I will try tomorrow execute all commands, but quickly after checking code, seem that enable/disable/move tests/etc.. deal only with composer.json that use my-vendor/my-package (path) and there is also a Str::slug(). So I think it will works fine. I will update you.

**Comment by bernhardh** [comment]
Any updates to this? It would be great, if it can be merged!

**Comment by thewebartisan7** [comment]
I have no time to update here, but I was using this last months and found no issue. I just have not time to review all tests and write new if required.

**Comment by sebastienheyd** [comment]
I proposed a new PR #113 

Hope this one will be merged...
